Fedisa/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'static/index'

  get 'static/about'

  get 'static/faq'

  get 'static/legal'

  get 'static/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static#index"
end

Fedisa/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Fedisa/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Fedisa/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Fedisa/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end

  def about
  end

  def faq
  end

  def legal
  end

  def contact
  end
end

Fedisa/app/helpers/application_helper.rb
module ApplicationHelper
end

Fedisa/app/helpers/static_helper.rb
module StaticHelper
end

Fedisa/app/views/layouts/_footer.html.erb
<footer class ="main-footer">
  <ul class ="main-footer__list__left">
    <li class ="main-footer__list__left__item main-footer__list__left__item--email"><a href="#">Email</a></li>
    <li class ="main-footer__list__left__item main-footer__list__left__item--skype"><a href="#">Skype</a></li>
    <li class ="main-footer__list__left__item main-footer__list__left__item--phone"><a href="#">Phone</a></li>
  </ul>
  <ul class ="main-footer__list__right">
    <li class ="main-footer__list__right__item main-footer__list__right__item--instagram"><a href="#" class="instagram">Instagram</a></li>
    <li class ="main-footer__list__right__item main-footer__list__right__item--facebook"><a href="#" class="facebook">Facebook</a></li>
    <li class ="main-footer__list__right__item main-footer__list__right__item--twitter"><a href="#" class="twitter">Twitter</a></li>
  </ul>
</footer>

Fedisa/app/views/layouts/_navigation.html.erb
<a href="<%= static_index_path %>" class="top__logo logo"><%= image_tag("logo.svg")%></a>
<nav class ="top__navigation navigation">
  <ul class ="top__navigation__list">
    <% if user_signed_in? %>
      <li class ="top__navigation__list__link top__navigation__list__link--active"><%= link_to 'Home',static_index_path %></li>
      <li class ="top__navigation__list__link"><%= link_to 'Contact',static_contact_path %></li>
      <li class ="top__navigation__list__link"><%= link_to 'FAQ',static_faq_path %></li>
      <li class ="top__navigation__list__link"><%= link_to 'Legal',static_legal_path %></li>
      <li class ="top__navigation__list__link"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li class ="top__navigation__list__link top__navigation__list__link--active"><%= link_to 'Home',static_index_path %></li>
      <li class ="top__navigation__list__link"><%= link_to 'Contact',static_contact_path %></li>
      <li class ="top__navigation__list__link"><%= link_to 'FAQ',static_faq_path %></li>
      <li class ="top__navigation__list__link"><%= link_to 'Legal',static_legal_path %></li>
      <li class ="top__navigation__list__link"><%= link_to 'Login', new_user_session_path %></li>
      <li class ="top__navigation__list__link"><%= link_to 'Register', new_user_registration_path %></li>
    <% end %>
  </ul>
</nav>

Fedisa/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Fedisa</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="top">
      <%= render 'layouts/navigation' %>
    </header>
    <!-- <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <% unless flash.empty? %>
      <script type="text/javascript">
        <% flash.each do |f| %>
          <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
          toastr['<%= type %>']('<%= f[1] %>');
        <% end %>
      </script>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>